### ISSUE TITLE
DaemonSet "csi-node-driver" is invalid

### ISSUE THREAD

**Issue by agaffney** [tigera/operator#2249] opened 2022-10-31 20:43 UTC
## Expected Behavior

All pods are successfully launched by the operator.

## Current Behavior

When the operator tries to create the `csi-node-driver` Deployment, it gets an error:

```
DaemonSet.apps "csi-node-driver" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: "kubelet-dir", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]
```

## Possible Solution

N/A

## Steps to Reproduce (for bugs)

1. Have an EKS 1.21 cluster
2. Deploy `v3.24.3` of the helm chart with `installation.kubernetesProvider=EKS`

## Context

The `csi-node-driver` Deployment failing to create causes the `calico-node` pods to be endlessly created and terminated.

## Your Environment

* Operating System and version: EKS 1.21

**Comment by lwr20** [comment] 2022-11-02 14:03
v3.24 doesn't support k8s 1.21?
https://projectcalico.docs.tigera.io/getting-started/kubernetes/requirements#supported-versions

**Comment by lwr20** [comment] 2022-11-02 14:05
Be aware of this if you're updating the EKS k8s version though: https://docs.aws.amazon.com/eks/latest/userguide/ebs-csi.html

**Comment by agaffney** [comment] 2022-11-02 14:42
It's not clear if k8s 1.21 is the problem, and I can't easily upgrade my cluster(s) yet to test. All I know if that the latest chart version with the versions of the Tigera operator and Calico that is uses by default result in that invalid resource error when the operator tries to create the DaemonSet. This does not happen with the previous minor version of the chart (and the versions of those components that it uses by default)

**Comment by lwr20** [comment] 2022-11-02 15:04
> I can't easily upgrade my cluster(s) yet to test
Then you need to use a version of Calico that does support k8s 1.21.  i.e. calico v3.23.x 

Kubernetes APIs change all the time, its not possible for operator to support every version of kubernetes with every version of Calico.  We do try to ensure that there's always a range though.

**Comment by agaffney** [comment] 2022-11-02 16:16
Does Calico v3.24.x officially not support k8s v1.21 (because it's broken), or is it just not tested on it?

**Comment by lwr20** [comment] 2022-11-02 16:35
> Does Calico v3.24.x officially not support k8s v1.21 (because it's broken), or is it just not tested on it?

"support" is a bit nebulous in an open source project - you're always free to do whatever you like with it.  

But [that doc](https://projectcalico.docs.tigera.io/archive/v3.24/getting-started/kubernetes/requirements#supported-versions) gives the list of k8s versions where we'd consider it to be a _bug_ if it didn't work with v3.24.  So in that sense, yes, this combination isn't supported.

**Comment by krmichelos** [comment] 2022-11-03 14:55
We are seeing the same error on EKS 1.22 with platform version eks.6

**Comment by kyle-rf** [comment] 2022-11-06 01:38
I'm experiencing the same issue on bare-metal K8s 1.25.3.

**Comment by EmilyShepherd** [comment] 2022-11-06 14:43
Also getting this on a fresh install (bare metal k8s v1.25.0 - tigera-operator-v3.24.4):

```
{"level":"error","ts":1667745113.0094,"logger":"controller_installation","msg":"ResourceUpdateError","Request.Namespace":"default","Request.Name":"sh.helm.release.v1.tigera-operator-1667744253.v1","ResourceUpdateError":"Error creating / updating resource","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"github.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1351\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"error","ts":1667745113.0108948,"msg":"Reconciler error","controller":"tigera-installation-controller","object":{"name":"sh.helm.release.v1.tigera-operator-1667744253.v1","namespace":"default"},"namespace":"default","name":"sh.helm.release.v1.tigera-operator-1667744253.v1","reconcileID":"5eed793e-f5b0-4b6e-8d2d-e3d03d937c04","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

The kubelet dir does exist on the node in the standard location:

```
# ls -la /mnt/var/lib/kubelet/
total 72
drwxr-xr-x    8 root     root          4096 Nov  6 13:28 .
drwxr-xr-x   11 root     root          4096 Nov  6 14:17 ..
-rw-r--r--    1 root     root           966 Nov  6 13:28 config.yaml
-rw-------    1 root     root            62 Jan  1  1970 cpu_manager_state
drwxr-xr-x    2 root     root          4096 Nov  6 13:33 device-plugins
-rw-r--r--    1 root     root            89 Nov  3 00:19 graceful_node_shutdown_state
-rw-r--r--    1 root     root           176 Nov  6 13:28 kubeadm-flags.env
-rw-------    1 root     root            61 Jan  1  1970 memory_manager_state
drwxr-xr-x    2 root     root          4096 Nov  1 21:16 pki
drwxr-x---    2 root     root          4096 Jan  1  1970 plugins
drwxr-x---    2 root     root          4096 Jan  1  1970 plugins_registry
drwxr-x---    2 root     root          4096 Nov  6 13:28 pod-resources
drwxr-x---   31 root     root          4096 Nov  6 14:42 pods
```

**Comment by kyle-rf** [comment] 2022-11-12 19:26
@tmjd  I do not.  I was on version 3.19 when I did an upgrade to 3.24.4.  It was working before the upgrade.

I am seeing a different issue with the csi-node-driver daemonset now.  For me the cluster I'm working on is just for testing so I deleted everything for tigera and calico from the cluster and removed `/var/lib/calico` from the nodes and did a fresh install of Tigera-Operator v3.24.5.  It looks like the operator scaled the csi-node-driver DS to zero automatically right at install because there is a missing service account.

Describing the csi-node-driver daemonset shows this in events:
`Error creating: pods "csi-node-driver-" is forbidden: error looking up service account calico-system/csi-node-driver: serviceaccount "csi-node-driver" not found`

I don't mean to detract from the OP's original issue.  Though deleting everything and reinstalling to the latest version has led to a different issue for me.

**Comment by ArchiFleKs** [comment] 2022-11-14 11:53
I have the same issue on EKS 1.23 `v1.23.13-eks-fb459a0`. I thought it was an upgrade issue. I tried deleting the DS but it is not recreated with the same error.

**Comment by aquam8** [comment] 2022-11-18 02:42
EBS CSI driver should NOT be a requirement, that would be very annoying. It does not come pre-installed on EKS anymore, i do not use it, and would be reluctant to add just because of Calico in my use-case.

Same as @ArchiFleKs , i'm on EKS 1.23, was running Calico 3.24.1 fine. Now updated to 3.24.5 and this is happening.
AFAIK this error only happens in the tigera/operator pod. calico-node or typha is not showing problems.

Thank you

**Comment by ArchiFleKs** [comment] 2022-11-18 02:46
> EBS CSI driver should NOT be a requirement, that would be very annoying. It does not come pre-installed on EKS anymore, i do not use it, and would be reluctant to add just because of Calico in my use-case.
> 
> Same as @ArchiFleKs , i'm on EKS 1.23, was running Calico 3.24.1 fine. Now updated to 3.24.5 and this is happening.
> AFAIK this error only happens in the tigera/operator pod. calico-node or typha is not showing problems.
> 
> Thank you

For information I'm using EBS CSI driver install via the official helm chart. But I don't see the relation here. The CSI driver installed by calico is another CSI driver right ? Non related to EBS ?

**Comment by Josh-Tigera** [comment] 2022-11-21 20:04
> Describing the csi-node-driver daemonset shows this in events:
Error creating: pods "csi-node-driver-" is forbidden: error looking up service account calico-system/csi-node-driver: serviceaccount "csi-node-driver" not found

@kyle-rf This is a separate issue you're hitting here with respect to the service name that I've recently submitted a fix for to our operator repo. The fix will be available in the next rebuild (eg. 3.24.6).

With respect to the "invalid" issue everyone is seeing I've been trying to reproduce the issue but have been unable to due to some unrelated blocking issues that I've only recently overcome. I'll prioritize this one now that I'm able to proceed and hopefully have an answer soon as well as an associated fix.

**Comment by Josh-Tigera** [comment] 2022-11-21 21:27
@ArchiFleKs could you provide detailed steps you ran to see the `"error":"DaemonSet.apps \"csi-node-driver\" is invalid` issue? I just setup a new EKS 1.23 cluster and installed Calico v3.24.3 via Helm and see the csi-node-driver pods running successfully.

**Comment by ArchiFleKs** [comment] 2022-11-23 09:26
@Josh-Tigera I'm not sure I really know when it started happening, I found this out when I upgraded from 3.24.4 to 3.24.5 but I might have been in a degraded state for longer.

What I don't understand is that now that I deleted the csi-node-driver from my cluster. I still get this error:

```
{"level":"error","ts":1669194644.1611958,"logger":"controller_installation","msg":"ResourceUpdateError","Request.Namespace":"tigera-operator","Request.Name":"sh.helm.release.v1.tigera-operator.v7","ResourceUpdateError":"Error creating / updating resource","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"github.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1351\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"error","ts":1669194644.1613555,"msg":"Reconciler error","controller":"tigera-installation-controller","object":{"name":"sh.helm.release.v1.tigera-operator.v7","namespace":"tigera-operator"},"namespace":"tigera-operator","name":"sh.helm.release.v1.tigera-operator.v7","reconcileID":"c2645d51-fab9-437e-afab-f07991aaf762","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

Which seems to be an operator issue because the object are not in my cluster anymore

**Comment by ArchiFleKs** [comment] 2022-11-23 09:36
@Josh-Tigera I can confirm that our production clusters are still running 3.24.1 whitout issue:
```
 k get tigerastatuses.operator.tigera.io
NAME        AVAILABLE   PROGRESSING   DEGRADED   SINCE
apiserver   True        False         False      21d
calico      True        False         False      25h
```

So issue seems to have happen during 3.24.5 upgrade

**Comment by ArchiFleKs** [comment] 2022-11-23 10:04
On a Kubernetes 1.22 running Calico v3.24.1 I tried to upgrade to v3.24.5 and getting the same error when operator restart with new version:
```
{"level":"error","ts":1669197747.275895,"logger":"controller_installation","msg":"ResourceUpdateError","Request.Namespace":"","Request.Name":"calico","ResourceUpdateError":"Error creating / updating resource","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"github.com/tigera/operator/pkg/controller/installation.(*ReconcileInstallation).Reconcile\n\t/go/src/github.com/tigera/operator/pkg/controller/installation/core_controller.go:1351\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:121\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:320\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
{"level":"error","ts":1669197747.2760081,"msg":"Reconciler error","controller":"tigera-installation-controller","object":{"name":"calico"},"namespace":"","name":"calico","reconcileID":"0f3068e2-a7df-4987-8fd4-908b9f95809b","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

**Comment by ArchiFleKs** [comment] 2022-11-23 10:41
@Josh-Tigera We believe to have found the issue.

[Helm v3 does not handle CRDs upgrade by default](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations). It means that every changes made in `crds` folder of the Helm charts are not upgraded and only apply at first install (that's why a clean install is OK for you)

When I applied manually the latest `crds` folders of the `v3.24.5` charts everything worked.

I believe you should either:

* release a separate charts to handle CRDs upgrade
* Tell user to upgrade CRDs separatly from Helm ([that's what kube-prometheus-stack is doing from example](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart))
* Have the CRDs packaged in `templates` but that would cause issues at first install because no guarantee that `installation` CRD would be installed before the actual installation object.

Here in my case I didn't have the new [spec](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Installation) `kubeletVolumePluginPath` in my CRD because it was not up to date

**Comment by jyotibhanot** [comment] 2022-11-23 13:30
@ArchiFleKs : How did you make it work?

**Comment by lwr20** [comment] 2022-11-23 13:39
@jyotibhanot the key sentence is:

> When I applied manually the latest crds folders of the v3.24.5 charts everything worked.

**Comment by jyotibhanot** [comment] 2022-11-23 13:43
> @jyotibhanot the key sentence is:
> 
> > When I applied manually the latest crds folders of the v3.24.5 charts everything worked.

I tried that but it didn't work. I did :
1. helm install calico projectcalico/tigera-operator --version v3.24.4 --namespace tigera-operator
2. k apply -f . ( inside crd folders)

**Comment by jyotibhanot** [comment] 2022-11-23 14:10
> > > @jyotibhanot the key sentence is:
> > > > When I applied manually the latest crds folders of the v3.24.5 charts everything worked.
> > 
> > 
> > I tried that but it didn't work. I did :
> > 
> > 1. helm install calico projectcalico/tigera-operator --version v3.24.5 --namespace tigera-operator
> > 2. k apply -f . ( inside crd folders)
> 
> Use `k replace` instead of apply, I got an error with the `installation` CRD being too big.
> 
> I just `k replace -f` or `k apply -f` all the crds present in the `crds` folder of charts v3.24.5

So install helm chart, then apply crds and then helm upgrade. Is that the order.

**Comment by ArchiFleKs** [comment] 2022-11-23 14:40
If it is your first install of the tigera operator and you do not have any Tigera/Calico CRDs in your cluster you can just `helm install` and it should work.

If you already have older crds (and tigera operator already installed) you just:
* `kubectl replace -f crds`
* `kubectl replace -f crds/calico`
* `helm upgrade` or `helm install` depending on if charts is already installed or not

**Comment by jyotibhanot** [comment] 2022-11-23 15:07
> If it is your first install of the tigera operator and you do not have any Tigera/Calico CRDs in your cluster you can just `helm install` and it should work.
> 
> If you already have older crds (and tigera operator already installed) you just:
> 
> * `kubectl replace -f crds`
> * `kubectl replace -f crds/calico`
> * `helm upgrade` or `helm install` depending on if charts is already installed or not

Fresh install doesn't work directly. I am using EKS 1.23 and calico latest version. I keep getting this error ```{"level":"error","ts":1669206159.4830186,"msg":"Reconciler error","controller":"tigera-installation-controller","object":{"name":"default"},"namespace":"","name":"default","reconcileID":"6c4d18a1-7ade-41f5-8e78-1a9e3c803d52","error":"DaemonSet.apps \"csi-node-driver\" is invalid: [spec.template.spec.volumes[2].hostPath.path: Required value, spec.template.spec.containers[0].volumeMounts[3].name: Not found: \"kubelet-dir\", spec.template.spec.containers[0].volumeMounts[3].mountPath: Required value]","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.12.3/pkg/internal/controller/controller.go:234"}
```

**Comment by ArchiFleKs** [comment] 2022-11-23 20:20
> > @Josh-Tigera We believe to have found the issue.
> 
> > [Helm v3 does not handle CRDs upgrade by default](https://helm.sh/docs/chart_best_practices/custom_resource_definitions/#some-caveats-and-explanations). It means that every changes made in crds folder of the Helm charts are not upgraded and only apply at first install (that's why a clean install is OK for you)
> > 
> > When I applied manually the latest crds folders of the v3.24.5 charts everything worked.
> > 
> > I believe you should either:
> > 
> > release a separate charts to handle CRDs upgrade
> > Tell user to upgrade CRDs separatly from Helm ([that's what kube-prometheus-stack is doing from example](https://github.com/prometheus-community/helm-charts/tree/main/charts/kube-prometheus-stack#upgrading-chart))
> > Have the CRDs packaged in templates but that would cause issues at first install because no guarantee that installation CRD would be installed before the actual installation object.
> > Here in my case I didn't have the new [spec](https://projectcalico.docs.tigera.io/reference/installation/api#operator.tigera.io/v1.Installation) kubeletVolumePluginPath in my CRD because it was not up to date
> 
> This is still a mystery to me because both v3.24.1 and v3.24.5 CRDs have the `kubeletVolumePlugin` field in the CRD (I just checked). There must be some other CRD difference that's aliasing to this same issue. I'll try a fresh install of v3.24.5 as well as an upgrade from v3.24.4 to v3.24.5 and see if I can figure out what's going on.

To be clear the issue might have happened before and I did not catch it. V3.24.1 was not a first install for me. I have been using tigera for more than a year on some clusters so my CRDs might have been older than v3.24.1. They just were never upgraded since my first install :/ 

So maybe a fresh install and upgrade from v3.24.1 to v3.24.5 is ok but what about people upgrading from older version ? Or having installed the chart a while ago for example. My guess is they are running very old versions of CRDs

**Comment by agaffney** [comment] 2022-12-09 23:02
I can confirm that updating the (numerous) CRDs manually allows me to upgrade to the `v3.24.5` release in the same cluster where I originally encountered this problem

**Comment by mgleung** [comment] 2023-01-19 22:03
It looks like this is the same issue as https://github.com/projectcalico/calico/issues/7030 so I am going to close this and track all progress there. Please let me know if there's anything else specific to this issue that we might need to reopen this for.

**Closed by mgleung** 2023-01-19 22:03 UTC
