### ISSUE TITLE
Support for ARM64

### ISSUE THREAD

**Issue by gfvirga** [tigera/operator#1270] opened 2021-04-23 01:50 UTC
Container image - quay.io/tigera/operator does not support arm64

## Expected Behavior
quay.io/tigera/operator to work on arm64 architecture

## Current Behavior
Getting the error
```
standard_init_linux.go:219: exec user process caused: exec format error
```
## Possible Solution
Create a container image using arm64 architecture

## Steps to Reproduce (for bugs)
Create a cluster on AWS using graviton nodes

## Context
I have a hybrid cluster and I got it to work by adding a nodeSelector for the operator to run on X86_64, but I was planning to only have ARM nodes in the future.

## Your Environment
AWS X86_64 and Graviton arm64 nodes.

**Comment by tmjd** [comment] 2021-04-23 19:25
Duplicate of #1241 and #1246

**Closed by tmjd** 2021-04-23 19:25 UTC
