### ISSUE TITLE
When unninstall 

### ISSUE THREAD

**Issue by davidpuziol** [tigera/operator#2807] opened 2023-08-17 14:14 UTC
## Expected Behavior
Once tigera-operator is installed to deploy calico on eks 1.27, when tigera is uninstalled the calico pods remain in the cluster.

## Steps to Reproduce (for bugs)

1. Create eks cluster version 1.27
2. Install tigera operator 1.35 using helm on namespace tigera-operator like oficial documentation
3. Unninstall tigera operator using helm
4. Check calico pods on 

## Your Environment
eks 1.27
All calicos images on 3.26.1 or 3.26.0 same problem
tigera 1..30.4  Same problem with 1.30.5

**Comment by tmjd** [comment] 2023-08-17 14:48
I think this is a duplicate of #2031. If you don't believe so please include more information clarifying how this is unique compared to #2031.

**Closed by tmjd** 2023-08-17 14:48 UTC

**Comment by davidpuziol** [comment] 2023-08-17 19:43
This is different. When i unninstall tigera operator, calico pods still there. Tigera Operator pod  disapear but all calico pods still running.

**Comment by tmjd** [comment] 2023-08-18 13:51
Does the Installation resource named `default` get removed in your scenario (you can check with `kubectl get installation`)? I would assume it does not because of the exact issue #2031 is about and because that resource remains then the calico-pods would remain.

Have you tried the sequence that I suggested in that issue [here](https://github.com/tigera/operator/issues/2031#issuecomment-1165608969) of removing the Installation `default` resource before uninstalling the operator?
